#ifndef NLECOMERROR_HEADER
#define NLECOMERROR_HEADER

#include "objbase.hpp"



#define E_NOT_SET                   _HRESULT_TYPEDEF_(0x8000000AL)

#define DISP_E_DIVBYZERO                   _HRESULT_TYPEDEF_(0x8000000BL)

#define E_UNEXPECTED    _HRESULT_TYPEDEF_(0x8000000CL)

#define E_NOT_VALID_STATE    _HRESULT_TYPEDEF_(0x8000000DL)



#endif

