#ifndef FPROPERTYPANEL_GLOBAL_H
#define FPROPERTYPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FPROPERTYPANEL_LIB
# define FPROPERTYPANEL_EXPORT Q_DECL_EXPORT
#else
# define FPROPERTYPANEL_EXPORT Q_DECL_IMPORT
#endif

#endif // FPR