#ifndef FSMEDIAPLAYERVIEW_GLOBAL_H
#define FSMEDIAPLAYERVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FSMEDIAPLAYVIEW_LIB
# define FSMEDIAPLAYVIEW_EXPORT Q_DECL_EXPORT
#else
# define FSMEDIAPLAYVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // FSMEDIAPLAYERVIEW_GLOBAL_H
