#ifndef FSTIMELINEVIEW_GLOBAL_H
#define FSTIMELINEVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FSTIMELINEVIEW_LIB
# define FSTIMELINEVIEW_EXPORT Q_DECL_EXPORT
#else
# define FSTIMELINEVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // FSTIMELINEVIEW_GLOBAL_H
