#ifndef FMEDIAPLAYERVIEW_GLOBAL_H
#define FMEDIAPLAYERVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FMEDIAPLAYERVIEW_LIB
# define FMEDIAPLAYERVIEW_EXPORT Q_DECL_EXPORT
#else
# define FMEDIAPLAYERVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // FMEDIAPLAYERVIEW_GLOBAL_H
