#ifndef FTIMELINEVIEW_GLOBAL_H
#define FTIMELINEVIEW_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef FTIMELINEVIEW_LIB
# define FTIMELINEVIEW_EXPORT Q_DECL_EXPORT
#else
# define FTIMELINEVIEW_EXPORT Q_DECL_IMPORT
#endif

#endif // FTIMELINEVIEW_GLOBAL_H
